events { worker_connections 1024; }

http {
    # Definición del entorno BLUE (Rama main - Puerto 3001 del host o IP interna)
    # Al estar Nginx en la misma red 'jenkinsnet', puede usar el nombre del contenedor de main si lo tuviera,
    # o la IP del host de docker (172.18.0.1) que le da salida al puerto mapeado 3001.
    upstream blue_env {
        server 172.18.0.4:3001; 
    }

    # Definición del entorno GREEN (Rama develop - Puerto 80 del contenedor jenkins-docker)
    upstream green_env {
        server jenkins-docker:80;
    }

    server {
        listen 80;
        server_name amazingdiv.com www.amazingdiv.com;

        location / {
            # CAMBIO DE ENTORNO (SWITCH BLUE/GREEN):
            # Para pasar a Blue, cambias 'green_env' por 'blue_env' y reinicias Nginx
            proxy_pass http://green_env; 
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded-for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}